### ISSUE TITLE
[Bug] Canais do YouTube aparecem com a etiqueta filme (print no comentário)

### ISSUE THREAD

**Issue by henriquesouza** [MyKidsWatch/MKW.Client#69]
![image](https://github.com/MyKidsWatch/MKW.Client/assets/82476540/7da0ded1-cb2d-47e9-b3f9-35b8f89e25c2)
![image](https://github.com/MyKidsWatch/MKW.Client/assets/82476540/3347473a-e2fd-4d46-8925-c30b423918b2)

**Comment by lukkanog** [comment]
@henriquesouza Corrigido na branch develop :)
